sudo: required
services:
    - docker 

before_install: 
    - docker build -t dockerbopeng/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true dockerbopeng/react-test npm test 

after_success:
    - docker build -t dockerbopeng/multi-client ./client 
    - docker build -t dockerbopeng/multi-nginx ./nginx 
    - docker build -t dockerbopeng/multi-server ./server 
    - docker build -t dockerbopeng/multi-worker ./worker 
    # Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those iamges and push them to docker hub.
    - docker push dockerbopeng/multi-client 
    - docker push dockerbopeng/multi-nginx 
    - docker push dockerbopeng/multi-server 
    - docker push dockerbopeng/multi-worker 